[package]
name = "pcls"
version = "0.1.0"
edition = "2024"

[dependencies]
winit = { version = "0.30", features = ["rwh_06"] }
rand = "0.8"
rayon = "1.10.0"
glow = "0.17"
glutin = "0.32"
glutin-winit = "0.5"
raw-window-handle = "0.6"
atomic_float = "1.1.0"

[profile.release]
debug = true
opt-level = 3
